---
- name: Set OpenSSH ClientAliveCountMax
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Set ClientAliveCountMax value
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?(ClientAliveCountMax).*'
        line: 'ClientAliveCountMax 3'
        backup: yes
      register: ssh_clientalivecountmax_changed
      changed_when: ssh_clientalivecountmax_changed.changed

    - name: Restart OpenSSH service
      service:
        name: ssh
        state: restarted
      when: ssh_clientalivecountmax_changed.changed
