---
- name: Ensure lockdown=confidentiality in the kernel command line
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Check current kernel command line
      shell: cat /proc/cmdline
      register: cmdline_result
      changed_when: false
      failed_when: false

    - name: Set lockdown=confidentiality in the kernel command line
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="lockdown=confidentiality"'
      when: "'lockdown=confidentiality' not in cmdline_result.stdout"

    - name: Update GRUB configuration
      command: update-grub
      when: "'lockdown=confidentiality' not in cmdline_result.stdout"

    - name: Reboot the system
      command: shutdown -r now
      async: 0
      poll: 0
      when: "'lockdown=confidentiality' not in cmdline_result.stdout"
