---
- name: Set OpenSSH ClientAliveCountMax
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install psad package
      apt:
        name: psad
        state: present
      become: true
